### ISSUE TITLE
変数名の説明

### ISSUE THREAD

**Issue by sugaikota** [c2cb/ProjExD#1]
https://github.com/c2cb/ProjExD/blob/53f218f2b1787678e0056a3ddaf860b414c98f10/ex01/alphabet.py#L14
その変数がどのように使われているかを説明するとよさそうです

**Comment by c2cb** [comment]
コメントをして頂いてありがとうございます。
時間が足りない分、説明などがおろそかになってしまってしまったので、これからは説明を書く余裕を持てるように頑張りたいと思います。ありがとうございました。
