### ISSUE TITLE
文字コード

### ISSUE THREAD

**Issue by c0b21107de** [c2cb/ProjExD#2]
https://github.com/c2cb/ProjExD/blob/53f218f2b1787678e0056a3ddaf860b414c98f10/ex01/alphabet.py#L6
大文字の文字コードは65~90なのでよかったら利用してください

**Comment by c2cb** [comment]
コメントをして頂いてありがとうございます。
とても助かります、頂いた知識でこれからも様々なプログラミングで活用できるように頑張りたいと思います。ありがとうございました。
