### ISSUE TITLE
改行が多すぎるように感じます

### ISSUE THREAD

**Issue by c0b21021c3** [c2cb/ProjExD#3]
https://github.com/c2cb/ProjExD/blob/53f218f2b1787678e0056a3ddaf860b414c98f10/ex01/alphabet.py#L33
改行が多ければ見やすくなりそうですが、多すぎると繋がりが分かりにくいと感じます。

**Comment by c2cb** [comment]
コメントをして頂いてありがとうございます。
時間が限られた中、私はひたすらコードを書くことしか頭にありませんでした。そのことで、説明や改行を怠ってしまいました。これからはもっと余裕を持って説明や見目に力を入れられるように頑張りたいと思います。ありがとうございました。
